#
  # Copyright (c) 2026 Metaform Systems, Inc.
  #
  # This program and the accompanying materials are made available under the
  # terms of the Apache License, Version 2.0 which is available at
  # https://www.apache.org/licenses/LICENSE-2.0
  #
  # SPDX-License-Identifier: Apache-2.0
  #
  # Contributors:
  #      Metaform Systems, Inc. - initial API and implementation
  #


{{- if .Values.redline.enabled }}
{{- $c := .Values.redline }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redline
  namespace: {{ include "cpd.namespace" . }}
  labels:
    app: redline
    type: edcv-app
    {{- include "cpd.labels" . | nindent 4 }}
spec:
  replicas: {{ $c.replicas }}
  selector:
    matchLabels:
      app: redline
  template:
    metadata:
      labels:
        app: redline
        platform: edcv
        type: edcv-app
    spec:
      # ServiceAccount created by the platform chart; jwtlet maps it to the
      # "redline" participant context.
      serviceAccountName: {{ $c.serviceAccountName }}
      containers:
        - name: redline
          image: {{ include "cpd.image" (dict "img" $c.image "ctx" $) }}
          imagePullPolicy: {{ include "cpd.pullPolicy" (dict "policy" $c.imagePullPolicy "ctx" $) }}
          ports:
            - containerPort: 8081
              name: http
              protocol: TCP
          envFrom:
            - configMapRef:
                name: redline-config
          {{- with $c.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /api/public/health
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 3
            timeoutSeconds: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /api/public/health
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 3
            timeoutSeconds: 1
            failureThreshold: 10
          volumeMounts:
            - name: jwtlet-subject-token
              mountPath: /var/run/secrets/jwtlet
              readOnly: true
      volumes:
        {{- include "cpd.jwtletSubjectTokenVolume" . | nindent 8 }}
---
apiVersion: v1
kind: Service
metadata:
  name: redline
  namespace: {{ include "cpd.namespace" . }}
  labels:
    app: redline
    {{- include "cpd.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: redline
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httproute-redline
  namespace: {{ include "cpd.namespace" . }}
  labels:
    {{- include "cpd.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.global.gatewayName }}
      kind: Gateway
      sectionName: http
  hostnames:
    - {{ .Values.global.host }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /redline
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: redline
          port: 8081
          weight: 1
{{- end }}
