#
# Copyright (c) 2025 Metaform Systems, Inc.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
#
# Contributors:
#      Metaform Systems, Inc. - initial API and implementation
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cfm-tenant-manager
  namespace: edc-v
  labels:
    app: tenant-manager
    platform: edcv
    type: edcv-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenant-manager
  template:
    metadata:
      labels:
        app: tenant-manager
        platform: edcv
        type: edcv-app
    spec:
      containers:
        - name: tenant-manager
          image: ghcr.io/eclipse-cfm/cfm/tmanager:latest
          imagePullPolicy: Always
          command: [ "/tmanager" ]
          args: [
            "--mode=debug"
          ]
          envFrom:
            - configMapRef:
                name: telemetry-config
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /etc/appname
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: tm-config
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: tenant-manager
  namespace: edc-v
spec:
  selector:
    app: tenant-manager
  ports:
    - port: 8080
      targetPort: 8080
      name: http

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: tenant-manager
  namespace: edc-v
spec:
  parentRefs:
    - name: edcv-gateway
      kind: Gateway
      sectionName: http
  hostnames:
    - jad.localhost
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api/tm
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /api/v1alpha1
        - type: ExtensionRef
          extensionRef:
            group: traefik.io
            kind: Middleware
            name: jwt-auth-tenant-manager-api
      backendRefs:
        - name: tenant-manager
          port: 8080
          weight: 1
