#
# Copyright (c) 2025 Metaform Systems, Inc.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
#
# Contributors:
#      Metaform Systems, Inc. - initial API and implementation
#

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tx-dataplane-config
  namespace: edc-v
data:
  # base config
  edc.hostname: "tx-dataplane.edc-v.svc.cluster.local"
  edc.vault.hashicorp.url: "http://vault.edc-v.svc.cluster.local:8200"
  edc.vault.hashicorp.token: "root"
  edc.participant.id: "did:web:identityhub.edc-v.svc.cluster.local%3A7083:tx"
  edc.participant.context.id: "tx-connector-context"

  edc.iam.did.web.use.https: "false"
  edc.iam.credential.revocation.mimetype: "application/json"

  # web config
  web.http.port: "8080"
  web.http.path: "/api"
  web.http.public.port: "8081"
  web.http.public.path: "/api/public"
  web.http.control.port: "8084"
  web.http.control.path: "/api/control"
  web.http.proxy.port: "8186"
  web.http.proxy.path: "/api/proxy"

  # TX config
  edc.transfer.proxy.token.signer.privatekey.alias: "tx-proxy-token-signer-key-alias"
  edc.transfer.proxy.token.verifier.publickey.alias: "tx-proxy-token-verifier-key-alias"
  tractusx.edc.participant.bpn: "BPNL00000000000000000"
  edc.iam.sts.oauth.token.url: "http://identityhub.edc-v.svc.cluster.local:7084/api/sts/token"
  edc.iam.sts.oauth.client.id: "did:web:identityhub.edc-v.svc.cluster.local%3A7083:tx"
  edc.iam.sts.oauth.client.secret.alias: "tx-connector-alias"
  edc.iam.issuer.id: "did:web:identityhub.edc-v.svc.cluster.local%3A7083:tx"
  tx.edc.iam.dcp.bdrs.server.url: "http://tx-bdrs.edc-v.svc.cluster.local:8083/api/directory"
  tx.edc.vault.secrets: "tx-connector-alias:vqtcS7dXxMMY7NgW"
  edc.iam.trusted-issuer.issuer.id: "did:web:issuerservice.edc-v.svc.cluster.local%3A10016:issuer"

  edc.datasource.default.url: "jdbc:postgresql://postgres.edc-v.svc.cluster.local:5432/txdataplanedb"
  edc.datasource.default.user: "txconnector"
  edc.datasource.default.password: "txconnector"

  edc.dpf.selector.url: "http://tx-connector.edc-v.svc.cluster.local:8083/api/control/v1/dataplanes"
  OTEL_JAVAAGENT_ENABLED: "false"
  JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=1044"