#
# Copyright (c) 2025 Metaform Systems, Inc.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
#
# Contributors:
#      Metaform Systems, Inc. - initial API and implementation
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cfm-agents
  namespace: edc-v
  labels:
    app: cfm-agents
    platform: edcv
    type: edcv-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cfm-agents
  template:
    metadata:
      labels:
        app: cfm-agents
        platform: edcv
        type: edcv-app
    spec:
      containers:
        - name: keycloak-agent
          image: ghcr.io/eclipse-cfm/cfm/kcagent:latest
          imagePullPolicy: Always
          command: [ "/kcagent" ]
          args: [
            "--mode=debug"
          ]
          envFrom:
            - configMapRef:
                name: telemetry-config
          volumeMounts:
            - name: keycloak-agent-config
              mountPath: /etc/appname
              readOnly: true
        - name: edcv-agent
          image: ghcr.io/eclipse-cfm/cfm/edcvagent:latest
          imagePullPolicy: Always
          command: [ "/edcvagent" ]
          args: [
            "--mode=debug"
          ]
          envFrom:
            - configMapRef:
                name: telemetry-config
          volumeMounts:
            - name: edcv-agent-config
              mountPath: /etc/appname
              readOnly: true
        - name: ih-agent
          image: ghcr.io/eclipse-cfm/cfm/ihagent:latest
          imagePullPolicy: Always
          command: [ "/ihagent" ]
          args: [
            "--mode=debug"
          ]
          envFrom:
            - configMapRef:
                name: telemetry-config
          volumeMounts:
            - name: ih-agent-config
              mountPath: /etc/appname
              readOnly: true
        - name: registration-agent
          image: ghcr.io/eclipse-cfm/cfm/regagent:latest
          imagePullPolicy: Always
          command: [ "/regagent" ]
          args: [
            "--mode=debug"
          ]
          envFrom:
            - configMapRef:
                name: telemetry-config
          volumeMounts:
            - name: registration-agent-config
              mountPath: /etc/appname
              readOnly: true
        - name: onboarding-agent
          image: ghcr.io/eclipse-cfm/cfm/obagent:latest
          imagePullPolicy: Always
          command: [ "/obagent" ]
          args: [
            "--mode=debug"
          ]
          envFrom:
            - configMapRef:
                name: telemetry-config
          volumeMounts:
            - name: onboarding-agent-config
              mountPath: /etc/appname
              readOnly: true
      volumes:
        - name: keycloak-agent-config
          configMap:
            name: keycloak-agent-config
        - name: edcv-agent-config
          configMap:
            name: edcv-agent-config
        - name: ih-agent-config
          configMap:
            name: ih-agent-config
        - name: registration-agent-config
          configMap:
            name: reg-agent-config
        - name: onboarding-agent-config
          configMap:
            name: ob-agent-config
        - name: ih-keyrotate-agent-config
          configMap:
            name: ih-keyrotate-agent-config
      restartPolicy: Always
